name: "tagged-release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag: '
        required: true
        default: 'v'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ github.event.inputs.tag }}
          files: |
            docs/README.md
